name: Build and Release ChodeMantra Executables

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag name (e.g., v2.1.0)'
        required: true
      release_title:
        description: 'Release title'
        required: true
      release_description:
        description: 'Release description'
        required: true
        type: multiline
      prerelease:
        description: 'Set as pre-release'
        required: true
        type: boolean
        default: false

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'

      - name: Get package version
        run: echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $env:GITHUB_ENV
        shell: powershell

      - name: Install Node.js dependencies
        run: npm install

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build normal .exe
        run: npm run dist -- --publish never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Python-embedded .exe
        run: |
          pyinstaller --onefile `
            --add-data "sun.ico;." `
            --add-data "sun.png;." `
            --add-data "index.html;." `
            --add-data "index.js;." `
            --add-data "rendered.js;." `
            --add-data "styles.css;." `
            --add-data "requirements.txt;." `
            --icon sun.ico `
            --name ChodeMantra-Embedded `
            type_snippet.py
        shell: powershell

      - name: Verify build artifacts
        run: |
          dir dist
          if (!(Test-Path "dist/Chodemantra Setup ${{ env.PACKAGE_VERSION }}.exe")) { 
            Write-Error "Normal .exe not found"
            exit 1
          }
          if (!(Test-Path "dist/ChodeMantra-Embedded.exe")) { 
            Write-Error "Python-embedded .exe not found"
            exit 1
          }
        shell: powershell

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event_name == 'workflow_dispatch' && github.inputs.tag_name || github.ref }}
          release_name: ${{ github.event_name == 'workflow_dispatch' && github.inputs.release_title || format('Release {0}', github.ref) }}
          body: ${{ github.event_name == 'workflow_dispatch' && github.inputs.release_description || format('ChodeMantra Release {0}', github.ref) }}
          prerelease: ${{ github.event..inputs.prerelease || false }}
          draft: false

      - name: Upload Normal .exe
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/Chodemantra Setup ${{ env.PACKAGE_VERSION }}.exe
          asset_name: Chodemantra Setup ${{ env.PACKAGE_VERSION }}.exe
          asset_content_type: application/octet-stream

      - name: Upload Python-Embedded .exe
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/ChodeMantra-Embedded.exe
          asset_name: ChodeMantra-Embedded-${{ github.event_name == 'workflow_dispatch' && github.inputs.tag_name || github.ref_name }}.exe
          asset_content_type: application/octet-stream
